name: CI

on:
  push:
    branches: ["main"]

jobs:
  checks:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          cache: true
      - name: Formatting
        run: pnpm run fmt
      - name: Linting
        run: pnpm run lint
